Repository approvers/discoxy, pull requests merged in 2020-10, with the labels that each got.

#3 [追加] スタート画面の追加完了
  main.py
Labels: enhancement

#7 [変更] Viewファイルに移動した
  lib/view.py
  main.py
Labels: enhancement

#9 †修正† Linuxパス取得周りでガバがあったので修正
  lib/model/discord_entry.py
Labels: enhancement

#14 [修正] 各種リファクタ
  lib/controller/controller.py
  lib/controller/parser.py
  lib/controller/utils.py
  lib/model/discord_entry.py
  lib/model/proxy_setting.py
  lib/model/utils.py
  lib/utils.py
  lib/view/utils.py
  lib/view/view.py
  main.py
Labels: help wanted

#15 [変更] 大規模見直し (ConfigObjectの作成)
  lib/controller/controller.py
  lib/controller/parser.py
  lib/controller/start_discord.py
  lib/controller/validate.py
  lib/model/config_object.py
  lib/model/discord_entry.py
  lib/model/exceptions.py
  lib/model/proxy_setting.py
  lib/model/validator.py
  lib/view/view.py
  main.py
Labels: enhancement, help wanted
